name: PR title check

on:
  pull_request:
    types: [opened, edited, reopened]

env:
  PR_TITLE_PATTERN: "^\[[A-Z]+-\d+\] \S+\s+\S+"

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR title format
      run: |
        if ! [[ ${{ github.event.pull_request.title }} =~ $PR_TITLE_PATTERN ]]; then
          echo "ERROR: Pull request title does not match required format."
          exit 1
        fi
