name: PR title check

on:
  pull_request:
    types: [opened, edited, reopened]

env:
  PR_TITLE_PATTERN: "^\\[[A-Z]+-[0-9]+\\] [^ ]+"

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - id: validate_title
        run: |
          if ! [[ "${{ github.event.pull_request.title }}" =~ $PR_TITLE_PATTERN ]]; then
            echo "ERROR: Pull request title does not match required format. E.g. [ONB-314] Add password reset flow"
            echo "valid_title=false" >> $GITHUB_OUTPUT
            exit 1
          fi
      
      - uses: actions/github-script@v6
        if: ${{ steps.validate_title.outputs.valid_title == 'false' }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Please fix the PR title to match this format: `[ONB-314] Add password reset flow`'
            })
