name: PR title check

on:
  pull_request:
    types: [opened, edited, reopened]

env:
  PR_TITLE_PATTERN: "^\\[[A-Z]+-[0-9]+\\] [^ ]+"

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "valid_title=[[ "${{ github.event.pull_request.title }}" =~ $PR_TITLE_PATTERN ]]" >> $GITHUB_OUTPUT
      
      - uses: actions/github-script@v6
        if: ${{ steps.stepid.outputs.valid_title > 0 }}"
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Please fix the PR title to match this format: `[ONB-314] Add password reset flow`'
            })
