name: PR title check

on:
  pull_request:
    types: [opened, edited, reopened]

env:
  PR_TITLE_PATTERN: "^\\[[A-Z]+-[0-9]+\\] [^ ]+"
  ERROR_MESSAGE: |
    Pull request title does not match required format. Example: `[ONB-314] Add password reset flow`.
    
    If there is no associated ticket number, you can disable the check by adding the label `no-jira-ticket`.

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - id: validate_title
        run: |
          if ! [[ "${{ github.event.pull_request.title }}" =~ $PR_TITLE_PATTERN ]]; then
            echo "ERROR: $ERROR_MESSAGE"
            exit 1
          fi
      
      - uses: actions/github-script@v6
        if: ${{ failure() }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.ERROR_MESSAGE
            })
