name: PR title check

on:
  pull_request:
    types: [opened, edited, reopened]

env:
  PR_TITLE_PATTERN: "^\\[[A-Z]+-[0-9]+\\] [^ ]+"
  ERROR_MESSAGE: |
    ⚠️ Pull request title does not match the required format. Example: `[ONB-314] Add password reset flow`.
    
    If this PR has no associated Jira Issue, you can disable the check by adding the label `no-jira-issue`.

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - id: validate_title
        if: "!contains(github.event.pull_request.labels.*.name, 'no-jira-issue')"
        run: |
          if ! [[ "${{ github.event.pull_request.title }}" =~ $PR_TITLE_PATTERN ]]; then
            echo "ERROR: $ERROR_MESSAGE"
            echo "is_valid=false" >> $GITHUB_OUTPUT
            exit 1
          fi
      
      - uses: actions/github-script@v6
        if: ${{ failure() && steps.validate_title.outputs.is_valid == 'false' }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.ERROR_MESSAGE
            })
