name: PR title check

on:
  pull_request:
    types: [opened, edited, reopened]

env:
  PR_TITLE_PATTERN: "^\\[[A-Z]+-[0-9]+\\] [^ ]+"

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - id: validate_title
        run: |
          valid_title=$([[ "${{ github.event.pull_request.title }}" =~ "${{ env.PR_TITLE_PATTERN }}" ]])
          echo $valid_title          
          echo "valid_title=$valid_title" >> $GITHUB_OUTPUT
          exit $valid_title
      
      - uses: actions/github-script@v6
        if: ${{ steps.validate_title.outputs.valid_title > 0 }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Please fix the PR title to match this format: `[ONB-314] Add password reset flow`'
            })
